/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

import MessageModel

class App {
    val greeting: String
        get() {
            val msg = MessageModel("Hello World!")
            return msg.text
        }
}

fun main() {
    println(App().greeting)
}
