/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

class App {
    val greeting: String
        get() {
            val msg = MessageModel("Hello World!")
            return msg.text
        }
}

fun main() {
    MessageService.print(MessageModel("Hello World!"))
    val person = Person("Alice", 29)
    println(person.description)
    person.age = 2
    println(person.description)

    person.city = "NY"
    println(person.city)
}
